### ISSUE TITLE
compatibility Nextcloud 23 / PHP8

### ISSUE THREAD

**Issue by der--flo** [cwilby/nextcloud-workflow-media-converter#198]
Hi there, i have issues with your wonderfull tool on nextcloud 23 (vanilla nextcloud:latest docker image, fresh install with mariadb and redis).

```
{"reqId":"xyCHS8pIWeaLKjBpXC12","level":3,"time":"2022-03-08T21:36:27+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#80","userAgent":"--","version":"23.0.2.1","exception":{"Exception":"Error","Message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#80","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":80,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Undefined array key \"convertMediaInParallel\"","/var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php",80]},{"file":"/var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":41,"function":"parseArguments","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[{"path":"/admin/files/teset.mov","outputExtension":"mp4","postConversionSourceRule":"delete","postConversionSourceRuleMoveFolder":null,"postConversionOutputRule":"keep","0":"And 3 more entries, set log level to debug to see all entries"}]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[{"path":"/admin/files/teset.mov","outputExtension":"mp4","postConversionSourceRule":"delete","postConversionSourceRuleMoveFolder":null,"postConversionOutputRule":"keep","0":"And 3 more entries, set log level to debug to see all entries"}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/html/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}

{"reqId":"xyCHS8pIWeaLKjBpXC12","level":3,"time":"2022-03-08T21:36:27+01:00","remoteAddr":"","user":"--","app":"workflow_media_converter","method":"","url":"--","message":"[Exception] :: (0) :: DateTime::__construct(): Failed to parse time string (no) at position 0 (n): The timezone could not be found in the database :: #0 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(259): DateTime->__construct('no')\n#1 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(108): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->conversionLockIsActive()\n#2 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(42): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->lockConversion()\n#3 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->run(Array)\n#4 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#5 /var/www/html/cron.php(128): OCP\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#6 {main}","userAgent":"--","version":"23.0.2.1"}
```
Maybe something with PHP8 or do i miss something regarding timezone settings ?

other backgroundjobs are running fine. 

```
Operating system: Linux 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 14:35:04 EST 2022 x86_64

Webserver: Apache/2.4.52 (Debian) (apache2handler)

Database: mysql 10.7.3

PHP version: 8.0.16

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, session, posix, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

Nextcloud version: 23.0.2 - 23.0.2.1

Updated from an older Nextcloud/ownCloud or fresh install:
fresh install 

Where did you install Nextcloud from: unknown
docker, nextcloud:latest
<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.9.0
 - activity: 2.15.0
 - admin_audit: 1.13.0
 - breezedark: 23.2.1
 - cloud_federation_api: 1.6.0
 - comments: 1.13.0
 - contactsinteraction: 1.4.0
 - dav: 1.21.0
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_pdfviewer: 2.4.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_trashbin: 1.13.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - firstrunwizard: 2.12.0
 - flow_notifications: 1.2.0
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - nextcloud_announcements: 1.12.0
 - notifications: 2.11.1
 - oauth2: 1.11.0
 - password_policy: 1.13.0
 - photos: 1.5.0
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - recommendations: 1.2.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - sharerenamer: 3.0.0
 - support: 1.6.0
 - survey_client: 1.11.0
 - systemtags: 1.13.0
 - text: 3.4.0
 - theming: 1.14.0
 - twofactor_backupcodes: 1.12.0
 - updatenotification: 1.13.0
 - user_status: 1.3.1
 - video_converter: 1.0.4
 - viewer: 1.7.0
 - weather_status: 1.3.0
 - workflow_media_converter: 1.3.5
 - workflowengine: 2.5.0
Disabled:
 - bruteforcesettings: 2.3.0
 - circles: 23.0.1
 - dashboard: 7.3.0
 - encryption
 - files_external
 - spreed: 13.0.3
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.derzbach.net"
    ],
    "overwriteprotocol": "https",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "23.0.2.1",
    "overwrite.cli.url": "https:\/\/cloud.derzbach.net",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "default_phone_region": "DE",
    "mail_sendmailmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpsecure": "tls",
    "app_install_overwrite": [
        "flow_notifications"
    ]
}


</details>

Cron Configuration: Array ( [backgroundjobs_mode] => webcron [lastcron] => 1646770201 )

External storages: files_external is disabled

Encryption: no

User-backends:

OC\User\Database

```

**Comment by der--flo** [comment]
i digged in a bit deeper. 

if the setting "enable parallel media conversion" is not ticked, this error occours:
`Undefined array key \"convertMediaInParallel\" at /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#80`

an additional error shows up when threads setting is changed:
`Undefined array key "conversion_lock" at /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php`

If the box is ticked, the workflow and the batch conversion works.

**Comment by cwilby** [comment]
@der--flo Thank you for digging, makes the issue shallower / easy to debug :)

I've pushed fixes for those errors in v1.3.6.  I'll do some testing with PHP 8 soon.
