### ISSUE TITLE
App not compatible with NC 25

### ISSUE THREAD

**Issue by Gymnae** [cwilby/nextcloud-workflow-media-converter#252]
## Steps to reproduce
1. Install app 
2. Attempt to create flow or manual batch transcode
3. flow creation fails with 

### Actual behaviour
Attempted with regex: /^.+\.(?:mkv|webm|wmv|mpe?g|avi|vob|dat|mov)$/i
Error message upon attempting to store flow:
"The configuration is invalid - No events are chosen"
Console message:
```
Failed to save operation
(anonymous) @ Rule.vue:150
```

Manual batches do not appear to start running

## Server configuration

**Operating system**: Official NC 25 docker image

**Nextcloud Version:** 25

**Comment by cwilby** [comment]
@Gymnae thank you for reporting the issue, several reports are intertwined with the NC25 release so forgive me if I miss a mark here.

I have gone through the NC25 breaking changes and applied those to this project, can you test if 1.6.2 resolves the issues you were having?

1.6.2 should

**Comment by Gymnae** [comment]
Hi @cwilby , sorry for my shite bug report :)
It was two things: The app was not ready for NC25 at the time I tried and I did miss setting the "When" setting. It appears to be working now :)

Thank you for your contribution to Nextcloud

**Comment by Gymnae** [comment]
Sorry, have to reopen this one. Neither my flow nor batch conversion appears to be doing something.
I'm running their official docker fpm image in a docker container, I find no logs to share.

Batch conversions get queued, but fail after some time without any actual conversion

**Comment by zackartz** [comment]
yeah, same issue here, status shows as "Queued" when batch converting flac files to mp3. nextcloud 25 running on arch linux.

**Comment by cwilby** [comment]
Identified and fixing these bugs.

```
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#81","userAgent":"--","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#81","Code":0,"Trace":[{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":81,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Undefined array key \"convertMediaInParallel\"","/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php",81]},{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":42,"function":"parseArguments","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/New folder/file_example_MOV_480_700kB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/New folder/file_example_MOV_480_700kB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":58,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"workflow_media_converter","method":"","url":"--","message":"[OCP\\Files\\NotFoundException] :: (0) :: /cwilby/files/New folder/file_example_MOV_480_700kB.mov :: #0 [internal function]: OC\\Files\\Node\\Root->get('/cwilby/files/N...')\n#1 /var/www/html/lib/private/Files/Node/LazyFolder.php(72): call_user_func_array(Array, Array)\n#2 /var/www/html/lib/private/Files/Node/LazyFolder.php(149): OC\\Files\\Node\\LazyFolder->__call('get', Array)\n#3 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(83): OC\\Files\\Node\\LazyFolder->get('/cwilby/files/N...')\n#4 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(42): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->parseArguments(Array)\n#5 /var/www/html/lib/public/BackgroundJob/Job.php(78): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->run(Array)\n#6 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(58): OCP\\BackgroundJob\\Job->start(Object(OC\\BackgroundJob\\JobList))\n#7 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(48): OCP\\BackgroundJob\\QueuedJob->start(Object(OC\\BackgroundJob\\JobList))\n#8 /var/www/html/cron.php(152): OCP\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#9 {main}","userAgent":"--","version":"25.0.0.18","data":{"app":"workflow_media_converter"}}
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined property: OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob::$outputFilePath at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#56","userAgent":"--","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Undefined property: OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob::$outputFilePath at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#56","Code":0,"Trace":[{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":56,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Undefined property: OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob::$outputFilePath","/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php",56]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/New folder/file_example_MOV_480_700kB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":58,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#81","userAgent":"--","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#81","Code":0,"Trace":[{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":81,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Undefined array key \"convertMediaInParallel\"","/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php",81]},{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":42,"function":"parseArguments","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/New folder/file_example_MOV_1920_2_2MB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/New folder/file_example_MOV_1920_2_2MB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":58,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"workflow_media_converter","method":"","url":"--","message":"[OCP\\Files\\NotFoundException] :: (0) :: /cwilby/files/New folder/file_example_MOV_1920_2_2MB.mov :: #0 [internal function]: OC\\Files\\Node\\Root->get('/cwilby/files/N...')\n#1 /var/www/html/lib/private/Files/Node/LazyFolder.php(72): call_user_func_array(Array, Array)\n#2 /var/www/html/lib/private/Files/Node/LazyFolder.php(149): OC\\Files\\Node\\LazyFolder->__call('get', Array)\n#3 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(83): OC\\Files\\Node\\LazyFolder->get('/cwilby/files/N...')\n#4 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(42): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->parseArguments(Array)\n#5 /var/www/html/lib/public/BackgroundJob/Job.php(78): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->run(Array)\n#6 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(58): OCP\\BackgroundJob\\Job->start(Object(OC\\BackgroundJob\\JobList))\n#7 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(48): OCP\\BackgroundJob\\QueuedJob->start(Object(OC\\BackgroundJob\\JobList))\n#8 /var/www/html/cron.php(152): OCP\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#9 {main}","userAgent":"--","version":"25.0.0.18","data":{"app":"workflow_media_converter"}}
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined property: OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob::$outputFilePath at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#56","userAgent":"--","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Undefined property: OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob::$outputFilePath at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#56","Code":0,"Trace":[{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":56,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Undefined property: OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob::$outputFilePath","/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php",56]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/New folder/file_example_MOV_1920_2_2MB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":58,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#81","userAgent":"--","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#81","Code":0,"Trace":[{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":81,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Undefined array key \"convertMediaInParallel\"","/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php",81]},{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":42,"function":"parseArguments","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/file_example_MOV_480_700kB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/file_example_MOV_480_700kB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":58,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"workflow_media_converter","method":"","url":"--","message":"[Exception] :: (0) :: Failed to parse time string (no) at position 0 (n): The timezone could not be found in the database :: #0 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(260): DateTime->__construct('no')\n#1 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(109): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->conversionLockIsActive()\n#2 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(43): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->lockConversion()\n#3 /var/www/html/lib/public/BackgroundJob/Job.php(78): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->run(Array)\n#4 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(58): OCP\\BackgroundJob\\Job->start(Object(OC\\BackgroundJob\\JobList))\n#5 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(48): OCP\\BackgroundJob\\QueuedJob->start(Object(OC\\BackgroundJob\\JobList))\n#6 /var/www/html/cron.php(152): OCP\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#7 {main}","userAgent":"--","version":"25.0.0.18","data":{"app":"workflow_media_converter"}}
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#81","userAgent":"--","version":"25.0.0.18","exception":{"Exception":"Error","Message":"Undefined array key \"convertMediaInParallel\" at /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php#81","Code":0,"Trace":[{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":81,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Undefined array key \"convertMediaInParallel\"","/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php",81]},{"file":"/var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php","line":42,"function":"parseArguments","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/file_example_MOV_1920_2_2MB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob","type":"->","args":[["/cwilby/files/file_example_MOV_1920_2_2MB.mov","mp4","delete",null,"keep","And 3 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":58,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"}]},{"file":"/var/www/html/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"zKt9c7i8N7gYXK3BC8UF","level":3,"time":"2022-11-08T19:05:02+00:00","remoteAddr":"","user":"--","app":"workflow_media_converter","method":"","url":"--","message":"[Exception] :: (0) :: Failed to parse time string (no) at position 0 (n): The timezone could not be found in the database :: #0 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(260): DateTime->__construct('no')\n#1 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(109): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->conversionLockIsActive()\n#2 /var/www/html/apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(43): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->lockConversion()\n#3 /var/www/html/lib/public/BackgroundJob/Job.php(78): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->run(Array)\n#4 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(58): OCP\\BackgroundJob\\Job->start(Object(OC\\BackgroundJob\\JobList))\n#5 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(48): OCP\\BackgroundJob\\QueuedJob->start(Object(OC\\BackgroundJob\\JobList))\n#6 /var/www/html/cron.php(152): OCP\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#7 {main}","userAgent":"--","version":"25.0.0.18","data":{"app":"workflow_media_converter"}}

```

**Comment by cwilby** [comment]
Version 1.6.4 has been released, which should fix the issues listed above. 

I was able to start a conversion both manually and via the flow engine.
