### ISSUE TITLE
Fails to delete files (unlink) - OC\\Files\\Node\\File->delete()

### ISSUE THREAD

**Issue by bugsyb** [cwilby/nextcloud-workflow-media-converter#382]
This is an ask for a help to further troubleshoot as am not sure if it is workflow-media-converter issue or core product issue.

## Steps to reproduce
Unknown (can be a problem with one of the other modules on the install. Vanilla install didn't show up this issue.

### Expected behaviour
Delete file after converstion.

### Actual behaviour
Fille gets converted by ffmpeg, but not deleted (or moved to a folder).

Problem seems to be coming from:
`OC\\Files\\Node\\File->delete()`

## Workflow Media Converter app

1.8.4

## Server configuration
Error reported is as follows:

```
Error Message:
[Error] :: (0) :: Call to a member function getUID() on null :: 

Stack Trace:
#0 /var/www/html/lib/private/EventDispatcher/ServiceEventListener.php(86): OCA\\OpenProject\\Listener\\BeforeNodeInsideOpenProjectGroupfilderChangedListener->handle(Object(OCP\\Files\\Events\\Node\\BeforeNodeDeletedEvent))
#1 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\\EventDispatcher\\ServiceEventListener->__invoke(Object(OCP\\Files\\Events\\Node\\BeforeNodeDeletedEvent), 'OCP\\\\Files\\\\Event...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#2 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'OCP\\\\Files\\\\Event...', Object(OCP\\Files\\Events\\Node\\BeforeNodeDeletedEvent))
#3 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(87): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(OCP\\Files\\Events\\Node\\BeforeNodeDeletedEvent), 'OCP\\\\Files\\\\Event...')
#4 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(99): OC\\EventDispatcher\\EventDispatcher->dispatch('OCP\\\\Files\\\\Event...', Object(OCP\\Files\\Events\\Node\\BeforeNodeDeletedEvent))
#5 /var/www/html/lib/private/Files/Node/HookConnector.php(149): OC\\EventDispatcher\\EventDispatcher->dispatchTyped(Object(OCP\\Files\\Events\\Node\\BeforeNodeDeletedEvent))
#6 /var/www/html/lib/private/legacy/OC_Hook.php(105): OC\\Files\\Node\\HookConnector->delete(Array)
#7 /var/www/html/lib/private/Files/View.php(1290): OC_Hook::emit('OC_Filesystem', 'delete', Array)
#8 /var/www/html/lib/private/Files/View.php(1165): OC\\Files\\View->runHooks(Array, '/topfolder/subfolder...')
#9 /var/www/html/lib/private/Files/View.php(729): OC\\Files\\View->basicOperation('unlink', '/username/files...', Array)
#10 /var/www/html/lib/private/Files/Node/File.php(131): OC\\Files\\View->unlink('/username/files...')
#11 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(195): OC\\Files\\Node\\File->delete()
#12 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(170): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->handlePostConversionSourceFile()
#13 /var/www/html/custom_apps/workflow_media_converter/lib/BackgroundJobs/ConvertMediaJob.php(65): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->handlePostConversion()
#14 /var/www/html/lib/public/BackgroundJob/Job.php(78): OCA\\WorkflowMediaConverter\\BackgroundJobs\\ConvertMediaJob->run(Array)
#15 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(57): OCP\\BackgroundJob\\Job->start(Object(OC\\BackgroundJob\\JobList))
#16 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\\BackgroundJob\\QueuedJob->start(Object(OC\\BackgroundJob\\JobList))
#17 /var/www/html/cron.php(152): OCP\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))
#18 {main}

User Agent: --

Version: 26.0.5.1

Data: {"app": "workflow_media_converter"}
```

This could be related to:
- https://github.com/owncloud/music/issues/1068#issuecomment-1566244178

But it should be fixed already given NC versions.

- Music, Quota and Retention apps disabled already.

**Comment by bugsyb** [comment]
If it helps, here is a list of apps:
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - audioplayer: 3.4.0
  - bookmarks: 13.1.1
  - bruteforcesettings: 2.6.0
  - calendar: 4.4.4
  - checksum: 1.2.2
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.3.2
  - contactsinteraction: 1.7.0
  - cookbook: 0.10.2
  - dashboard: 7.6.0
  - dav: 1.25.0
  - external: 5.1.1
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_automatedtagging: 1.16.1
  - files_downloadactivity: 1.16.0
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_photospheres: 1.26.4
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - forms: 3.3.1
  - gpxedit: 5.0.4
  - gpxmotion: 0.1.0
  - gpxpod: 5.0.12
  - health: 1.6.2
  - integration_openproject: 2.4.4
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - maps: 1.1.1
  - mediadc: 0.3.6
  - memories: 5.4.1
  - metadata: 0.19.0
  - news: 23.0.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.8.1
  - notifications: 2.14.0
  - oauth2: 1.14.1
  - phonetrack: 0.7.6
  - photos: 2.2.0
  - podcast: 0.3.1
  - polls: 5.2.0
  - previewgenerator: 5.3.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - radio: 1.0.3
  - recommendations: 1.5.0
  - related_resources: 1.1.0
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - sharerenamer: 3.2.0
  - sharingpath: 0.4.4
  - spreed: 16.0.5
  - survey_client: 1.14.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - tasks: 0.15.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - unsplash: 2.2.1
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - user_usage_report: 1.10.0
  - video_converter: 1.0.6
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflow_media_converter: 1.8.4
  - workflow_script: 1.11.2
  - workflowengine: 2.8.0
Disabled:
  - duplicatefinder: 0.0.15 (installed 0.0.15)
  - encryption: 2.14.0 (installed 2.10.0)
  - facerecognition: 0.9.12
  - files_retention: 1.15.0 (installed 1.15.0)
  - loganalyzer: 0.0.4 (installed 0.0.4)
  - mail: 2.2.5 (installed 2.2.5)
  - music: 1.8.4 (installed 1.8.4)
  - ocdownloader-orig: 1.8.1
  - ocsms: 2.2.0 (installed 2.2.0)
  - password_policy: 1.16.0 (installed 1.12.0)
  - quota_warning: 1.17.0 (installed 1.17.0)
  - recognize: 3.7.0 (installed 3.7.0)
  - support: 1.9.0 (installed 1.5.0)
  - twofactor_totp: 8.0.0
  - user_ldap: 1.16.0

**Comment by bugsyb** [comment]
After further investigation identified module:
- integration_openproject

Once this is disabled files are deleted.

**Comment by cwilby** [comment]
I went to create that pull request in OpenProject, and they've locked contribution and I wasn't able to open an issue.

If you want to take this further, you'll need to point the OpenProject team to this ticket via their support channels.

<img width="1275" alt="image" src="https://github.com/cwilby/nextcloud-workflow-media-converter/assets/13686317/cf07685a-59bb-4449-accd-e404dd03f98c">

**Comment by bugsyb** [comment]
Thank you. Completely weird from OpenProject team side.

**Comment by bugsyb** [comment]
Would you mind to share the changes/PR in diff form with me? I'd patch this locally if they don't want to fix issues on their end.

Thanks again for all done on this!

**Comment by cwilby** [comment]
@bugsyb - Coming back to this, it looks like their change should have solved the problem in the same way my change would have.

Separately, I tested creating a conversion job that deletes the source file, and it worked.  The reason for the deletion not happening may be something else at this point.  

Some questions:  
1) Is the Music app installed?
2) What is your current NC version?
